optical_flow:
    ros__parameters:
        sensor_timeout: 0.5
        parent_frame: odom
        child_frame: optical_flow_front_link
        # board: paa5100 # [pmw3901, paa5100]
        board: 3901-l0x # [pmw3901, paa5100]
        scaler: -800.0
        rotation: 0 # [0, 90, 180, 270]
        publish_tf: true
        baud: 115200
        port: /dev/matek
        poll_rate: 10.0
